query getPokemonDetail($pokemonName: String!) {
  pokemon(name: $pokemonName) {
    id
    sprites {
      back_default
      front_default
    }
    types {
      slot
      type {
        id
        url
        name
      }
    }
    moves {
      move {
        id
        url
        name
      }
    }
  }
}
